<script>
import {db} from './firebase';
export let uid;
export let project;

  let projectDetailBuilderTitle = "";
  let projectDetailBuilderContent = "";
  let sectionParagraph =
    "  Web design encompasses many different skills and disciplines in the production and maintenance of websites. The different areas of web design    include web graphic design; interface design; authoring, including    standardised code and proprietary software; user experience design; and    search engine optimization. Often many individuals will work in teams    covering different aspects of the design process, although some designers will cover them all. The term web design is normally used to describe the    design process relating to the front-end (client side) design of a website    including writing mark up. Web design partially overlaps web engineering in  the broader scope of web development. Web designers are expected to have an awareness of usability and if their role involves creating mark up then they are also expected to be up to date with web accessibility guidelines.";
  let projectDetail = [
    {
      title: "Tools and Technologies",
      content:
        "Web designers use a variety of different tools depending on what part of the production process they are involved in. These tools are updated over time by newer standards and software but the principles behind them remain the same. Web graphic designers use vector and raster graphics packages to create web-formatted imagery or design prototypes. Technologies used to create websites include standardized mark-up, which can be hand-coded or generated by WYSIWYG editing software. There is also proprietary software based on plug-ins that bypasses the client’s browser versions. These are often WYSIWYG but with the option of using the software’s scripting language. Search engine optimization tools may be used to check search engine ranking and suggest improvements. Other tools web designers might use include mark up validators and other testing tools for usability and accessibility to ensure their web sites meet web accessibility guidelines.​"
    }
  ];
updateWhatWeDo();
function updateWhatWeDo(){
    db.collection("users")
    .doc(uid)
    .collection("proposals")
    .doc(project)
    .update({
      WhatWeDo: { ...projectDetail},
      wwdSectionParagraph:sectionParagraph,
    });
}
  function projectDetailBuilder() {
    if (projectDetailBuilderTitle != "" && projectDetailBuilderContent != "") {
      projectDetail.push({
        title: projectDetailBuilderTitle,
        content: projectDetailBuilderContent
      });
      projectDetail = projectDetail;
      updateWhatWeDo();
      projectDetailBuilderTitle = "";
      projectDetailBuilderContent = "";
    } else {
      alert("Please Enter Valid Content");
    }
  }

  function deleteItem(index) {
    var filtered = projectDetail.filter(function(value, i, arr) {
      return index != i;
    });
    projectDetail = filtered;
    updateWhatWeDo();
  }
</script>

<style>
  .builder {
    padding: 20px 10px;
    border-radius: 5px;
    background: rgb(240, 239, 239);
  }
  .builder button {
    margin-top: 10px;
    background: #3498db;
    color: white;
    padding: 8px;
    width: 80px;
    border: none;
    cursor: pointer;
  }
  input,
  textarea {
    border: none;
    width: 100%;
    border-bottom: 2px dotted #333;
  }
  .builder input,
  .builder textarea {
    width: 100%;
    border: none;
    padding: 8px;
  }
  .project-item {
    margin-bottom: 20px;
  }
  .project-item button {
    font-size: 80%;
    color: white;
    border: none;
    background: red;
    display: block;
    float: right;
  }
  /* Print CSS */

  @media print {
  }
</style>

<div class="section">
  <h2>What We Do</h2>
  <p class="print">{sectionParagraph}</p>
  <textarea class="screen" on:blur={updateWhatWeDo} bind:value={sectionParagraph} placeholder="Enter Content" />
  {#each projectDetail as detail, i}
    <div class="project-item">
      <h3>{detail.title}</h3>
      <p>{detail.content}</p>
      <button on:click={() => deleteItem(i)}>Delete</button>
      <div class="clearfix" />
    </div>
  {/each}
  <div class="builder">
    <input
      type="text"
      bind:value={projectDetailBuilderTitle}
      placeholder="Enter Title" />
    <textarea
      bind:value={projectDetailBuilderContent}
      placeholder="Enter Content" />
    <button on:click={projectDetailBuilder}>Add</button>
  </div>
</div>
